routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\TrainingTopicController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CropController;
use App\Http\Controllers\KhmergeoController;
use App\Http\Controllers\ProvincesController;
use App\Http\Controllers\DistrictsController;
use App\Http\Controllers\CommunesController;
use App\Http\Controllers\VillagesController;
use App\Http\Controllers\ExportsController;
use App\Http\Controllers\ImportExportController;
use App\Http\Controllers\ImportsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

// Export Import Controller
Route::get('import-export', [ImportExportController::class,'index'])->name('import-export');
Route::get('export', [ImportExportController::class,'export'])->name('export');
Route::post('import', [ImportExportController::class,'import'])->name('import');

Auth::routes();


Route::group(['middleware' => 'auth'], function () {


Route::get('buyers-export', [ExportsController::class, 'buyerExport'])->name('buyers-export');
Route::get('purchasesales-export', [ExportsController::class, 'purchasesalesExport'])->name('purchasesales-export');
Route::get('mainpurchasesales-export', [ExportsController::class, 'mainpurchasesalesExport'])->name('mainpurchasesales-export');
Route::get('suppliers-export', [ExportsController::class, 'suppliersExport'])->name('suppliers-export');
Route::get('producers-export', [ExportsController::class, 'producersExport'])->name('producers-export');
Route::get('bmps-export', [ExportsController::class, 'bmpsExport'])->name('bmps-export');
Route::get('investments-export', [ExportsController::class, 'investmentsExport'])->name('investments-export');
Route::get('loans-export', [ExportsController::class, 'loansExport'])->name('loans-export');
Route::get('jobs-export', [ExportsController::class, 'jobsExport'])->name('jobs-export');
Route::get('maintrainings-export', [ExportsController::class, 'maintrainingsExport'])->name('maintrainings-export');
Route::get('allinonecontacts-export', [ExportsController::class, 'allinonecontactsExport'])->name('allinonecontacts-export');


Route::get('import-tmp-contacts/upload-file', [ImportsController::class, 'index'])->name('import-tmp-contacts.uploadfile');
Route::post('import-tmp-contacts/final-import', [ImportsController::class, 'finalImport'])->name('import-tmp-contacts.finalimport');
Route::post('import-tmp-contacts/import', [ImportsController::class, 'import'])->name('import-tmp-contacts.import');
Route::post('import-tmp-contacts/clear-all', [App\Http\Controllers\ImportsController::class,'clearall'])->name('import-tmp-contacts.clearall');
Route::delete('import-tmp-contacts/destroy/{id}', [App\Http\Controllers\ImportsController::class,'destroy'])->name('import-tmp-contacts.destroy');
//Route::resource('import-tmp-contacts', App\Http\Controllers\ImportsController::class);

Route::post('investments/approve', [App\Http\Controllers\InvestmentsController::class,'approve'])->name('investments.approve');
Route::resource('investments', App\Http\Controllers\InvestmentsController::class);

Route::post('loans/approve', [App\Http\Controllers\LoansController::class,'approve'])->name('loans.approve');
Route::resource('loans', App\Http\Controllers\LoansController::class);

Route::post('jobs/approve', [App\Http\Controllers\JobsController::class,'approve'])->name('jobs.approve');
Route::resource('jobs', App\Http\Controllers\JobsController::class);

Route::resource('bmps', App\Http\Controllers\BmpsController::class);

Route::resource('producers', App\Http\Controllers\ProducersController::class);

Route::post('suppliers/approve', [App\Http\Controllers\SuppliersController::class,'approve'])->name('suppliers.approve');
Route::resource('suppliers', App\Http\Controllers\SuppliersController::class);

Route::get('buyers/hide/{id}', [App\Http\Controllers\BuyersController::class, 'hide'])->name('buyers.hide');
Route::post('buyers/approve', [App\Http\Controllers\BuyersController::class,'approve'])->name('buyers.approve');
Route::resource('buyers', App\Http\Controllers\BuyersController::class);

Route::post('mainpurchasesales/approve', [App\Http\Controllers\MainpurchasesalesController::class,'approve'])->name('mainpurchasesales.approve');
Route::resource('mainpurchasesales', App\Http\Controllers\MainpurchasesalesController::class);

Route::post('purchasesales/approve', [App\Http\Controllers\PurchasesalesController::class,'approve'])->name('purchasesales.approve');
Route::resource('purchasesales', App\Http\Controllers\PurchasesalesController::class);

Route::post('maintrainings/approve', [App\Http\Controllers\MainTrainingsController::class,'approve'])->name('maintrainings.approve');
Route::get('maintrainings/addparticipants/{id}', [App\Http\Controllers\MainTrainingsController::class,'addparticipants'])->name('maintrainings.addparticipants');
Route::resource('maintrainings', App\Http\Controllers\MainTrainingsController::class);
Route::post('maintrainings/storeparticipant', [App\Http\Controllers\MainTrainingsController::class,'storeparticipant'])->name('maintrainings.storeparticipant');
Route::resource('maintrainingsmeta', App\Http\Controllers\MainTrainingsMetaController::class);

Route::post('allinonecontacts/restore', [App\Http\Controllers\AllinoneContactsController::class,'restore'])->name('allinonecontacts.restore');
Route::resource('allinonecontacts', App\Http\Controllers\AllinoneContactsController::class);

//Route::get('/', function () {    return view('welcome'); });

// Route::group(['middleware' => ['auth']], function() {
Route::resource('permissions', PermissionController::class);
Route::resource('roles', RoleController::class);
Route::resource('users', UserController::class);
Route::resource('products', ProductController::class);
// });

Route::resource('references/crops', CropController::class);
Route::get('references/crops/softdelete/{id}',['as'=>'crops.softdelete','uses'=>'App\Http\Controllers\CropController@softdelete']);
Route::get('crops/get-crops',['as'=>'crops.getCrops','uses'=>'App\Http\Controllers\CropController@getCrops']);

Route::resource('references/training-topics', TrainingTopicController::class);
Route::get('training-topics/get-training-topics',['as'=>'training-topics.getTrainingTopics','uses'=>'App\Http\Controllers\TrainingTopicController@getTrainingTopics']);

// Resource Route for article.
//Route::resource('articles', ArticleController::class);
//Route::get('articles/softdelete/{id}',['as'=>'articles.softdelete','uses'=>'App\Http\Controllers\ArticlesController@softdelete']);
//Route::get('get-permissions', [PermissionController::class, 'getPermissions'])->name('get-permissions');
//Route::get('get-articles', [ArticleController::class, 'getArticles'])->name('get-articles');


Route::get('references/khmergeos/get-khmergeos', [KhmergeoController::class,'getKhmergeos'])->name('get-khmergeos');
Route::get('references/khmergeos/fileImportExport',['as'=>'khmergeos.fileImportExport','uses'=>'App\Http\Controllers\KhmergeoController@fileImportExport']);
Route::get('references/khmergeos/file-export',['as'=>'khmergeos.file-export','uses'=>'App\Http\Controllers\KhmergeoController@file_export']);
Route::get('references/khmergeos/file-import',['as'=>'khmergeos.file-import','uses'=>'App\Http\Controllers\KhmergeoController@file_import']);
Route::resource('references/khmergeos', KhmergeoController::class);

Route::get('getProvince',[ProvincesController::class, 'getProvince'])->name('getProvince');
Route::get('getDistrict/{procode}',[DistrictsController::class, 'getDistrict'])->name('getDistrict');
Route::get('getCommune/{discode}',[CommunesController::class, 'getCommune'])->name('getCommune');
Route::get('getVillage/{comcode}',[VillagesController::class, 'getVillage'])->name('getVillage');

    Route::get('/route-cache', function() {
        $exitCode = Artisan::call('route:cache');
        return 'Routes cache cleared';
    });
    Route::get('/config-cache', function() {
        $exitCode = Artisan::call('config:cache');
        return 'Config cache cleared';
    });
    Route::get('/clear-cache', function() {
        $exitCode = Artisan::call('cache:clear');
        return 'Application cache cleared';
    });
    Route::get('/view-clear', function() {
        $exitCode = Artisan::call('view:clear');
        return 'View cache cleared';
    });


// Resource Route for article.
// Route::resource('references/training-topics', TrainingTopicController::class);
// Route for get articles for yajra post request.
// Route::get('get-training-topics', [TrainingTopicController::class, 'getTrainingTopics'])->name('get-training-topics');


// Route::post('references/training-topics/store',['as'=>'references.training-topics.store','uses'=>'App\Http\Controllers\TrainingTopicController@store']);
// Route::get('references/training-topics',['as'=>'references.training-topics.index','uses'=>'App\Http\Controllers\TrainingTopicController@index']);
// Route::get('references/training-topics/ajax',['as'=>'references.training-topics.ajax','uses'=>'App\Http\Controllers\TrainingTopicController@ajax']);
// Route::get('references/training-topics/create',['as'=>'references.training-topics.create','uses'=>'App\Http\Controllers\TrainingTopicController@create']);
// Route::post('references/training-topics/update/{id}',['as'=>'references.training-topics.update','uses'=>'App\Http\Controllers\TrainingTopicController@update']);

resources/views/all_contacts/show.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'show-xx'
])
@section('content')
 <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                    {{-- start --}}


                    <div class="row">
                        
                        <div class="col-lg-12 margin-tb">
                            <div class="pull-left">
                                    <h2> Show Crops</h2> 
                            </div>
                            <div class="pull-right"> 
                                <a class="btn btn-primary" href="{{ route('crops.index') }}"> Back</a> 
                            </div>
                        </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group"> <strong>Name:</strong> {{ $crop->name }} </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group"> <strong>Name Khmer:</strong> {{ $crop->name_kh }} </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group"> <strong>Base Price:</strong> {{ $crop->base_price }} </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group"> <strong>Description:</strong> {{ $crop->description }} </div>
                            </div>                        
                    </div>
                    {{-- end --}}
                    </div>
                </div>
            </div>
        </div>
 </div>


@endsection
{{-- 
@push('scripts')
    <script>
        $(document).ready(function () {
        
		});
  </script>
@endpush --}}

resources/views/all_contacts/upload_file.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'import-contacts'
])
@section('content')
 <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="pull-left">
                            <h4 class="card-title"> Import Contacts From Excel</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('import-tmp-contacts.import') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-8">
                                    <input type="file" name="file" class="form-control" required>
                                </div>
                                <div class="col-md-2">
                                    <div class="pull-right">
                                        <button class="btn btn-success" style="margin-top: 3px">Preview Contact</button>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="pull-right">
                                        <a href="../../excel_templates/import_contacts.xlsx" style="margin-top: 3px" class="btn btn-info">Download Template</a>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>

                </div>



            </div>

        </div>
     @if($preview_data->isNotEmpty())
     <div class="row">
         <div class="col-md-12">
             <div class="card">
                 <div class="card-header">
                     <div class="row">
                         <div class="col-md-8">
                             <h4 class="card-title"> Preview before Import</h4>
                         </div>
                         <div class="col-md-2">
                             <div class="pull-right">
                                 <form method="POST" action="{{ route('import-tmp-contacts.clearall') }}">
                                     @csrf
                                     <button type="submit" class="show_confirm btn btn-danger" data-toggle="tooltip" title='Clear All'>Clear All</button>
                                 </form>
                             </div>
                         </div>
                         <div class="col-md-2">
                             <div class="pull-right">
                                 <form method="POST" action="{{ route('import-tmp-contacts.finalimport') }}">
                                     @csrf
                                     <button type="submit" class="confirm_import btn btn-primary" data-toggle="tooltip" title='Import Contact'>Import Contact</button>
                                 </form>

{{--                                <a href="{{ route('import-tmp-contacts.finalimport') }}" style="margin-top: 3px" class="btn btn-success">Import Contact</a>--}}
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="card-body">
                     <table class="table">
                         <thead class=" text-primary">
                         <th>
                             ID
                         </th>
                         <th>
                             Name.English
                         </th>
                         <th>
                             Name.Khmer
                         </th>

                         <th>
                             Sex
                         </th>

                         <th>
                             Age
                         </th>

                         <th>
                             Phone
                         </th>

                         <th>
                             Province
                         </th>

                         <th>
                             District
                         </th>

                         <th>
                             Commune
                         </th>
                         <th>
                             Commune
                         </th>
                         <th>
                             Commune
                         </th>
                         <th>
                             Note
                         </th>
                         <th>
                             Table
                         </th>
                         <th class="text-right">
                             Action
                         </th>
                         </thead>
                         <tbody>

                             @foreach( $preview_data as $data)
                                 <tr>
                                     <td> {{ $data->id }} </td>
                                     <td> {{ $data->name_en }} </td>
                                     <td> {{ $data->name_kh }} </td>
                                     <td> {{ $data->sex }} </td>
                                     <td> {{ $data->age }} </td>
                                     <td> {{ $data->phone }} </td>
                                     <td> {{ $data->email }} </td>
                                     <td> {{ $data->proname }} </td>
                                     <td> {{ $data->disname }} </td>
                                     <td> {{ $data->comname }} </td>
                                     <td> {{ $data->vilname }} </td>
                                     <td> {{ $data->note }} </td>
                                     <td> {{ $data->tables }} </td>
                                     <td class="text-right">
                                         <form method="POST" action="{{ route('import-tmp-contacts.destroy', $data->id) }}">
                                             @csrf
                                             @method('DELETE')
                                             <input type="hidden" value="{{$data->id}}" name="id">
                                             <button type="submit" class="show_confirm btn btn-sm btn-danger" data-toggle="tooltip" title='Delete'><i class="nc-icon nc-simple-remove"></i></button>
                                         </form>
                                     </td>
                                 </tr>
                             @endforeach

                         </tbody>
                     </table>
                     <div class="card-footer d-flex align-items-center">
                         <p class="m-0 text-muted">Showing   {{$preview_data->count()}} entries</p>
                         <ul class="pagination m-0 ms-auto">
                             {{$preview_data->links()}}
                         </ul>
                     </div>

                 </div>
             </div>
         </div>
     </div>
     @endif
 </div>


@endsection
@push('scripts')
    <script>

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var id = $(this).data("id");
            event.preventDefault();
            swal({
                title: `Are you sure you want clear all contents in preview?`,
                text: "All preview content will be deleted forever.",
                icon: "warning",
                // buttons: true,
                // dangerMode: true,
                showCancelButton: true,
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                    // $(".preloader").fadeIn();
                });
        });
        $('.confirm_import').click(function(event) {
            var form =  $(this).closest("form");
            var id = $(this).data("id");
            event.preventDefault();
            swal({
                title: `Are you sure you want to import contact?`,
                text: "All information in preview page will be imported and cleared from preview.",
                icon: "success",
                // buttons: true,
                // dangerMode: true,
                showCancelButton: true,
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false
            })
                .then((willImport) => {
                    if (willImport) {
                        form.submit();
                    }
                    // $(".preloader").fadeIn();
                });
        });

        $(document).ready(function () {

		});
    </script>
@endpush