routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\TrainingTopicController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CropController;
use App\Http\Controllers\KhmergeoController;
use App\Http\Controllers\ProvincesController;
use App\Http\Controllers\DistrictsController;
use App\Http\Controllers\CommunesController;
use App\Http\Controllers\VillagesController;
use App\Http\Controllers\ExportsController;
use App\Http\Controllers\ImportExportController;
use App\Http\Controllers\ImportsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

// Export Import Controller
Route::get('import-export', [ImportExportController::class,'index'])->name('import-export');
Route::get('export', [ImportExportController::class,'export'])->name('export');
Route::post('import', [ImportExportController::class,'import'])->name('import');

Auth::routes();


Route::group(['middleware' => 'auth'], function () {


Route::get('buyers-export', [ExportsController::class, 'buyerExport'])->name('buyers-export');
Route::get('purchasesales-export', [ExportsController::class, 'purchasesalesExport'])->name('purchasesales-export');
Route::get('mainpurchasesales-export', [ExportsController::class, 'mainpurchasesalesExport'])->name('mainpurchasesales-export');
Route::get('suppliers-export', [ExportsController::class, 'suppliersExport'])->name('suppliers-export');
Route::get('producers-export', [ExportsController::class, 'producersExport'])->name('producers-export');
Route::get('bmps-export', [ExportsController::class, 'bmpsExport'])->name('bmps-export');
Route::get('investments-export', [ExportsController::class, 'investmentsExport'])->name('investments-export');
Route::get('loans-export', [ExportsController::class, 'loansExport'])->name('loans-export');
Route::get('jobs-export', [ExportsController::class, 'jobsExport'])->name('jobs-export');
Route::get('maintrainings-export', [ExportsController::class, 'maintrainingsExport'])->name('maintrainings-export');
Route::get('allinonecontacts-export', [ExportsController::class, 'allinonecontactsExport'])->name('allinonecontacts-export');


Route::get('import-tmp-contacts/upload-file', [ImportsController::class, 'index'])->name('import-tmp-contacts.uploadfile');
Route::post('import-tmp-contacts/final-import', [ImportsController::class, 'finalImport'])->name('import-tmp-contacts.finalimport');
Route::post('import-tmp-contacts/import', [ImportsController::class, 'import'])->name('import-tmp-contacts.import');
Route::post('import-tmp-contacts/clear-all', [App\Http\Controllers\ImportsController::class,'clearall'])->name('import-tmp-contacts.clearall');
Route::delete('import-tmp-contacts/destroy/{id}', [App\Http\Controllers\ImportsController::class,'destroy'])->name('import-tmp-contacts.destroy');
//Route::resource('import-tmp-contacts', App\Http\Controllers\ImportsController::class);

Route::post('investments/approve', [App\Http\Controllers\InvestmentsController::class,'approve'])->name('investments.approve');
Route::resource('investments', App\Http\Controllers\InvestmentsController::class);

Route::post('loans/approve', [App\Http\Controllers\LoansController::class,'approve'])->name('loans.approve');
Route::resource('loans', App\Http\Controllers\LoansController::class);

Route::post('jobs/approve', [App\Http\Controllers\JobsController::class,'approve'])->name('jobs.approve');
Route::resource('jobs', App\Http\Controllers\JobsController::class);

Route::resource('bmps', App\Http\Controllers\BmpsController::class);

Route::resource('producers', App\Http\Controllers\ProducersController::class);

Route::post('suppliers/approve', [App\Http\Controllers\SuppliersController::class,'approve'])->name('suppliers.approve');
Route::resource('suppliers', App\Http\Controllers\SuppliersController::class);

Route::get('buyers/hide/{id}', [App\Http\Controllers\BuyersController::class, 'hide'])->name('buyers.hide');
Route::post('buyers/approve', [App\Http\Controllers\BuyersController::class,'approve'])->name('buyers.approve');
Route::resource('buyers', App\Http\Controllers\BuyersController::class);

Route::post('mainpurchasesales/approve', [App\Http\Controllers\MainpurchasesalesController::class,'approve'])->name('mainpurchasesales.approve');
Route::resource('mainpurchasesales', App\Http\Controllers\MainpurchasesalesController::class);

Route::post('purchasesales/approve', [App\Http\Controllers\PurchasesalesController::class,'approve'])->name('purchasesales.approve');
Route::resource('purchasesales', App\Http\Controllers\PurchasesalesController::class);

Route::post('maintrainings/approve', [App\Http\Controllers\MainTrainingsController::class,'approve'])->name('maintrainings.approve');
Route::get('maintrainings/addparticipants/{id}', [App\Http\Controllers\MainTrainingsController::class,'addparticipants'])->name('maintrainings.addparticipants');
Route::resource('maintrainings', App\Http\Controllers\MainTrainingsController::class);
Route::post('maintrainings/storeparticipant', [App\Http\Controllers\MainTrainingsController::class,'storeparticipant'])->name('maintrainings.storeparticipant');
Route::resource('maintrainingsmeta', App\Http\Controllers\MainTrainingsMetaController::class);

Route::post('allinonecontacts/restore', [App\Http\Controllers\AllinoneContactsController::class,'restore'])->name('allinonecontacts.restore');
Route::resource('allinonecontacts', App\Http\Controllers\AllinoneContactsController::class);

//Route::get('/', function () {    return view('welcome'); });

// Route::group(['middleware' => ['auth']], function() {
Route::resource('permissions', PermissionController::class);
Route::resource('roles', RoleController::class);
Route::resource('users', UserController::class);
Route::resource('products', ProductController::class);
// });

Route::resource('references/crops', CropController::class);
Route::get('references/crops/softdelete/{id}',['as'=>'crops.softdelete','uses'=>'App\Http\Controllers\CropController@softdelete']);
Route::get('crops/get-crops',['as'=>'crops.getCrops','uses'=>'App\Http\Controllers\CropController@getCrops']);

Route::resource('references/training-topics', TrainingTopicController::class);
Route::get('training-topics/get-training-topics',['as'=>'training-topics.getTrainingTopics','uses'=>'App\Http\Controllers\TrainingTopicController@getTrainingTopics']);

// Resource Route for article.
//Route::resource('articles', ArticleController::class);
//Route::get('articles/softdelete/{id}',['as'=>'articles.softdelete','uses'=>'App\Http\Controllers\ArticlesController@softdelete']);
//Route::get('get-permissions', [PermissionController::class, 'getPermissions'])->name('get-permissions');
//Route::get('get-articles', [ArticleController::class, 'getArticles'])->name('get-articles');


Route::get('references/khmergeos/get-khmergeos', [KhmergeoController::class,'getKhmergeos'])->name('get-khmergeos');
Route::get('references/khmergeos/fileImportExport',['as'=>'khmergeos.fileImportExport','uses'=>'App\Http\Controllers\KhmergeoController@fileImportExport']);
Route::get('references/khmergeos/file-export',['as'=>'khmergeos.file-export','uses'=>'App\Http\Controllers\KhmergeoController@file_export']);
Route::get('references/khmergeos/file-import',['as'=>'khmergeos.file-import','uses'=>'App\Http\Controllers\KhmergeoController@file_import']);
Route::resource('references/khmergeos', KhmergeoController::class);

Route::get('getProvince',[ProvincesController::class, 'getProvince'])->name('getProvince');
Route::get('getDistrict/{procode}',[DistrictsController::class, 'getDistrict'])->name('getDistrict');
Route::get('getCommune/{discode}',[CommunesController::class, 'getCommune'])->name('getCommune');
Route::get('getVillage/{comcode}',[VillagesController::class, 'getVillage'])->name('getVillage');

    Route::get('/route-cache', function() {
        $exitCode = Artisan::call('route:cache');
        return 'Routes cache cleared';
    });
    Route::get('/config-cache', function() {
        $exitCode = Artisan::call('config:cache');
        return 'Config cache cleared';
    });
    Route::get('/clear-cache', function() {
        $exitCode = Artisan::call('cache:clear');
        return 'Application cache cleared';
    });
    Route::get('/view-clear', function() {
        $exitCode = Artisan::call('view:clear');
        return 'View cache cleared';
    });


// Resource Route for article.
// Route::resource('references/training-topics', TrainingTopicController::class);
// Route for get articles for yajra post request.
// Route::get('get-training-topics', [TrainingTopicController::class, 'getTrainingTopics'])->name('get-training-topics');


// Route::post('references/training-topics/store',['as'=>'references.training-topics.store','uses'=>'App\Http\Controllers\TrainingTopicController@store']);
// Route::get('references/training-topics',['as'=>'references.training-topics.index','uses'=>'App\Http\Controllers\TrainingTopicController@index']);
// Route::get('references/training-topics/ajax',['as'=>'references.training-topics.ajax','uses'=>'App\Http\Controllers\TrainingTopicController@ajax']);
// Route::get('references/training-topics/create',['as'=>'references.training-topics.create','uses'=>'App\Http\Controllers\TrainingTopicController@create']);
// Route::post('references/training-topics/update/{id}',['as'=>'references.training-topics.update','uses'=>'App\Http\Controllers\TrainingTopicController@update']);

resources/views/layouts/navbars/navs/auth.blade.php
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="#cambodiaharvest">{{$elementActive}}</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
            aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
{{--            <form>--}}
{{--                <div class="input-group no-border">--}}
{{--                    <input type="text" value="" class="form-control" placeholder="Search...">--}}
{{--                    <div class="input-group-append">--}}
{{--                        <div class="input-group-text">--}}
{{--                            <i class="nc-icon nc-zoom-split"></i>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </form>--}}
            <ul class="navbar-nav">
{{--                <li class="nav-item">--}}
{{--                    <a class="nav-link btn-magnify" href="#cambodiaharvest">--}}
{{--                        <i class="nc-icon nc-layout-11"></i>--}}
{{--                        <p>--}}
{{--                            <span class="d-lg-none d-md-block">{{ __('Stats') }}</span>--}}
{{--                        </p>--}}
{{--                    </a>--}}
{{--                </li>--}}
{{--                <li class="nav-item btn-rotate dropdown">--}}
{{--                    <a class="nav-link dropdown-toggle" href="http://#cambodiaharvest" id="navbarDropdownMenuLink"--}}
{{--                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">--}}
{{--                        <i class="nc-icon nc-bell-55"></i>--}}
{{--                        <p>--}}
{{--                            <span class="d-lg-none d-md-block">{{ __('Some Actions') }}</span>--}}
{{--                        </p>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">--}}
{{--                        <a class="dropdown-item" href="#">{{ __('Action') }}</a>--}}
{{--                        <a class="dropdown-item" href="#">{{ __('Another action') }}</a>--}}
{{--                        <a class="dropdown-item" href="#">{{ __('Something else here') }}</a>--}}
{{--                    </div>--}}
{{--                </li>--}}
                <li class="nav-item btn-rotate dropdown">
                    <a class="nav-link dropdown-toggle" href="http://#" id="navbarDropdownMenuLink2"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="nc-icon nc-settings-gear-65"></i>
                        <p>
                            <span class="d-lg-none d-md-block">{{ __('Account') }}</span>
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink2">
                        <form class="dropdown-item" action="{{ route('logout') }}" id="formLogOut" method="POST" style="display: none;">
                            @csrf
                        </form>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" onclick="document.getElementById('formLogOut').submit();">{{ __('Log out') }}</a>
                            <a class="dropdown-item" href="{{ route('profile.edit') }}">{{ __('My profile') }}</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/navbars/navs/guest.blade.php
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
    <div class="container">
        <div class="navbar-wrapper">
            <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="#pablo">{{ __('Monitoring and Evaluation') }}</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{ route('login') }}" class="nav-link">
                    <i class="nc-icon nc-layout-11"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                <li class="nav-item ">
                    <a href="{{ route('register') }}" class="nav-link">
                    <i class="nc-icon nc-book-bookmark"></i>{{ __('Register') }}
                    </a>
                </li>
                <li class="nav-item  active ">
                    <a href="{{ route('login') }}" class="nav-link">
                    <i class="nc-icon nc-tap-01"></i>{{ __('Login') }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/navbars/navs/navbmp.blade.php
{{--Bmps--}}
<li class="{{ $elementActive == 'list-bmps' || $elementActive == 'show-bmps' || $elementActive == 'create-bmps' || $elementActive == 'edit-bmps' ? 'active' : '' }}">
    <a data-toggle="collapse" aria-expanded="true" href="#menu_bmps">
        <i class="nc-icon nc-single-02"></i>
        <p>
            {{ __('BMPs') }}
            <b class="caret"></b>
        </p>
    </a>
    <div class="collapse {{ $elementActive == 'list-bmps' || $elementActive == 'show-bmps' || $elementActive == 'create-bmps' || $elementActive == 'edit-bmps' ? 'show' : '' }}" id="menu_bmps">
        <ul class="nav">
            <li class="{{ $elementActive == 'list-bmps' ? 'active' : '' }}">
                <a href="{{ route('bmps.index') }}">
                    <span class="sidebar-normal">{{ __(' List Bmps ') }}</span>
                </a>
            </li>
            <li class="{{ $elementActive == 'create-bmps' ? 'active' : '' }}">
                <a href="{{ route('bmps.create') }}">
                    <span class="sidebar-normal">{{ __(' Create New ') }}</span>
                </a>
            </li>
            @if ($elementActive == 'show-bmps')
                <li class="{{ $elementActive == 'show-bmps' ? 'active' : '' }}">
                    <a href="#show_bmp">
                        <span class="sidebar-normal">{{ __(' Show Bmp ') }}</span>
                    </a>
                </li>

            @endif
            @if ($elementActive == 'edit-bmps')
                <li class="{{ $elementActive == 'edit-bmps' ? 'active' : '' }}">
                    <a href="#edit_bmp">
                        <span class="sidebar-normal">{{ __(' Edit Bmp ') }}</span>
                    </a>
                </li>

            @endif

        </ul>
    </div>
</li>
{{--End Bmp--}}

resources/views/layouts/navbars/navs/navdashboard.blade.php
{{--Dashboard--}}
<li class="{{ $elementActive == 'db-overview' || $elementActive == 'db-charts' || $elementActive == 'db-project-year' || $elementActive == 'db-quarter' || $elementActive == 'db-subsector' ? 'active' : '' }}">
    <a data-toggle="collapse" aria-expanded="true" href="#menu_db">
        <i class="nc-icon nc-bank"></i>
        <p>
            {{ __('Dashboard') }}
            <b class="caret"></b>
        </p>
    </a>
    <div class="collapse {{ $elementActive == 'db-overview' || $elementActive == 'db-charts' || $elementActive == 'db-project-year' || $elementActive == 'db-quarter' || $elementActive == 'db-subsector' ? 'show' : '' }}" id="menu_db">
        <ul class="nav">
            <li class="{{ $elementActive == 'db-overview' ? 'active' : '' }}">
                <a href="{{ route('bmps.index') }}">
                    <span class="sidebar-normal">{{ __(' Overview ') }}</span>
                </a>
            </li>
            <li class="{{ $elementActive == 'db-charts' ? 'active' : '' }}">
                <a href="{{ route('bmps.create') }}">
                    <span class="sidebar-normal">{{ __(' Charts ') }}</span>
                </a>
            </li>
            <li class="{{ $elementActive == 'db-project-year' ? 'active' : '' }}">
                <a href="{{ route('bmps.create') }}">
                    <span class="sidebar-normal">{{ __(' Project Year ') }}</span>
                </a>
            </li>
            <li class="{{ $elementActive == 'db-quarter' ? 'active' : '' }}">
                <a href="{{ route('bmps.create') }}">
                    <span class="sidebar-normal">{{ __(' Quarter ') }}</span>
                </a>
            </li>
            <li class="{{ $elementActive == 'db-subsector' ? 'active' : '' }}">
                <a href="{{ route('bmps.create') }}">
                    <span class="sidebar-normal">{{ __(' Subsector ') }}</span>
                </a>
            </li>


        </ul>
    </div>
</li>
{{--End Dashboard--}}

resources/views/layouts/navbars/navs/navproducers.blade.php
{{--Producers--}}
<li class="{{ $elementActive == 'list-producers' || $elementActive == 'show-producers' || $elementActive == 'create-producers' || $elementActive == 'edit-producers' ? 'active' : '' }}">
    <a data-toggle="collapse" aria-expanded="true" href="#menu_producers">
        <i class="nc-icon nc-single-02"></i>
        <p>
            {{ __('Producers') }}
            <b class="caret"></b>
        </p>
    </a>
    <div class="collapse {{ $elementActive == 'list-producers' || $elementActive == 'show-producers' || $elementActive == 'create-producers' || $elementActive == 'edit-producers' ? 'show' : '' }}" id="menu_producers">
        <ul class="nav">
            <li class="{{ $elementActive == 'list-producers' ? 'active' : '' }}">
                <a href="{{ route('producers.index') }}">
                    <span class="sidebar-normal">{{ __(' List Producers ') }}</span>
                </a>
            </li>
            <li class="{{ $elementActive == 'create-producers' ? 'active' : '' }}">
                <a href="{{ route('producers.create') }}">
                    <span class="sidebar-normal">{{ __(' Create New ') }}</span>
                </a>
            </li>
            @if ($elementActive == 'show-producers')
                <li class="{{ $elementActive == 'show-producers' ? 'active' : '' }}">
                    <a href="#show_bmp">
                        <span class="sidebar-normal">{{ __(' Show Producer ') }}</span>
                    </a>
                </li>

            @endif
            @if ($elementActive == 'edit-producers')
                <li class="{{ $elementActive == 'edit-producers' ? 'active' : '' }}">
                    <a href="#edit_bmp">
                        <span class="sidebar-normal">{{ __(' Edit Producer ') }}</span>
                    </a>
                </li>

            @endif

        </ul>
    </div>
</li>
{{--End Producer--}}